let player;let musicPlaying=false;
window.onYouTubeIframeAPIReady=()=>{player=new YT.Player('ytPlayer',{events:{onReady:()=>{}}});};
const openBtn=document.getElementById('openBtn');const musicBtn=document.getElementById('musicBtn');
openBtn.addEventListener('click',()=>{document.getElementById('intro').classList.add('hide');document.body.classList.remove('locked');const main=document.getElementById('content');main.classList.add('show');main.setAttribute('aria-hidden','false');if(player?.playVideo){player.playVideo();musicPlaying=true;musicBtn.textContent='♫ pausar música';}makeHearts(18);});
musicBtn.addEventListener('click',()=>{document.getElementById('nossa-musica').scrollIntoView({behavior:'smooth',block:'center'});if(!player)return;if(musicPlaying){player.pauseVideo();musicBtn.textContent='♫ ouvir música';}else{player.playVideo();musicBtn.textContent='♫ pausar música';}musicPlaying=!musicPlaying;});
function updateCounter(){const start=new Date('2020-10-03T00:00:00-03:00');const diff=Math.max(0,Date.now()-start);document.getElementById('days').textContent=Math.floor(diff/86400000).toLocaleString('pt-BR');document.getElementById('hours').textContent=Math.floor(diff/3600000).toLocaleString('pt-BR');document.getElementById('minutes').textContent=Math.floor(diff/60000).toLocaleString('pt-BR');}updateCounter();setInterval(updateCounter,60000);
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
function makeHearts(total=12){for(let i=0;i<total;i++)setTimeout(()=>{const h=document.createElement('span');h.textContent=Math.random()>.5?'♡':'♥';h.style.left=Math.random()*100+'vw';h.style.fontSize=12+Math.random()*22+'px';h.style.animationDuration=4+Math.random()*4+'s';h.style.opacity=.25+Math.random()*.55;document.getElementById('hearts').appendChild(h);setTimeout(()=>h.remove(),8500)},i*170)}setInterval(()=>{if(!document.body.classList.contains('locked'))makeHearts(1)},1800);
function celebrate(){document.getElementById('answer').innerHTML='<div class="answer-pop">Então vem viver o para sempre comigo, minha princesa! ♡</div>';for(let i=0;i<70;i++){const s=document.createElement('span');s.className='burst';s.textContent=['♥','♡','✦'][i%3];s.style.left='50vw';s.style.top='70vh';s.style.color=i%3===2?'#d8ae63':'#ef6f9f';const a=Math.random()*Math.PI*2,d=80+Math.random()*300;s.style.setProperty('--x',Math.cos(a)*d+'px');s.style.setProperty('--y',Math.sin(a)*d+'px');document.body.appendChild(s);setTimeout(()=>s.remove(),1900)}}
document.getElementById('yesBtn').addEventListener('click',celebrate);document.getElementById('ofCourseBtn').addEventListener('click',celebrate);
